# Generated by Django 5.1.15 on 2026-03-22 05:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Phrase',
            fields=[
                ('id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('harari_latin', models.CharField(max_length=200)),
                ('harari_ethiopic', models.CharField(blank=True, default='', max_length=200)),
                ('harari_arabic', models.CharField(blank=True, default='', max_length=200)),
                ('english', models.CharField(max_length=300)),
                ('category', models.CharField(blank=True, default='', max_length=50)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['category', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Word',
            fields=[
                ('id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('harari_latin', models.CharField(max_length=100)),
                ('harari_ethiopic', models.CharField(blank=True, default='', max_length=100)),
                ('harari_arabic', models.CharField(blank=True, default='', max_length=100)),
                ('english', models.CharField(max_length=200)),
                ('category', models.CharField(max_length=50)),
                ('difficulty', models.IntegerField(choices=[(1, 'Easy'), (2, 'Medium'), (3, 'Hard')], default=1)),
                ('source', models.CharField(blank=True, default='', max_length=100)),
                ('verified', models.CharField(choices=[('pending', 'Pending'), ('verified', 'Verified'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('audio_file', models.FileField(blank=True, upload_to='audio/words/')),
                ('image', models.ImageField(blank=True, upload_to='images/words/')),
                ('audio_recorded', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['category', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Sentence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('harari_latin', models.CharField(max_length=500)),
                ('harari_ethiopic', models.CharField(blank=True, default='', max_length=500)),
                ('harari_arabic', models.CharField(blank=True, default='', max_length=500)),
                ('english', models.CharField(max_length=500)),
                ('lesson_context', models.TextField(blank=True, default='')),
                ('word', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sentences', to='vocabulary.word')),
            ],
            options={
                'ordering': ['word', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('unit', models.IntegerField()),
                ('order', models.IntegerField()),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, default='')),
                ('exercises', models.JSONField(default=list)),
                ('words', models.ManyToManyField(blank=True, related_name='lessons', to='vocabulary.word')),
            ],
            options={
                'ordering': ['unit', 'order'],
            },
        ),
        migrations.CreateModel(
            name='DictionaryEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('harari_latin', models.CharField(max_length=200)),
                ('english', models.TextField()),
                ('category', models.CharField(blank=True, default='', max_length=50)),
                ('notes', models.TextField(blank=True, default='')),
                ('word', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dictionary_entries', to='vocabulary.word')),
            ],
            options={
                'verbose_name_plural': 'dictionary entries',
                'ordering': ['harari_latin'],
            },
        ),
    ]
