# Generated by Django 5.1.15 on 2026-03-22 05:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('vocabulary', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ease_factor', models.FloatField(default=2.5)),
                ('interval', models.IntegerField(default=0)),
                ('repetitions', models.IntegerField(default=0)),
                ('next_review', models.DateTimeField()),
                ('status', models.CharField(choices=[('new', 'New'), ('learning', 'Learning'), ('mastered', 'Mastered')], default='new', max_length=20)),
            ],
            options={
                'verbose_name_plural': 'user progress',
            },
        ),
        migrations.CreateModel(
            name='UserStreak',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current', models.IntegerField(default=0)),
                ('last_date', models.DateField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'user streaks',
            },
        ),
        migrations.CreateModel(
            name='UserLessonProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('locked', 'Locked'), ('available', 'Available'), ('in_progress', 'In Progress'), ('completed', 'Completed')], default='locked', max_length=20)),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vocabulary.lesson')),
            ],
            options={
                'verbose_name_plural': 'user lesson progress',
            },
        ),
    ]
