# Generated by Django 5.1.15 on 2026-03-22 05:14

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Recording',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('audio_file', models.FileField(upload_to='recordings/')),
                ('mime_type', models.CharField(default='audio/webm', max_length=50)),
                ('sample_rate', models.IntegerField(default=48000)),
                ('duration', models.FloatField(default=0)),
                ('peak_amplitude', models.FloatField(blank=True, null=True)),
                ('clipping', models.BooleanField(default=False)),
                ('too_quiet', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Speaker',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('age_range', models.CharField(choices=[('18-25', '18-25'), ('26-35', '26-35'), ('36-45', '36-45'), ('46-55', '46-55'), ('56-65', '56-65'), ('65+', '65+')], max_length=10)),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other'), ('prefer_not_to_say', 'Prefer not to say')], max_length=20)),
                ('fluency_level', models.CharField(choices=[('native', 'Native'), ('fluent', 'Fluent'), ('partial', 'Partial'), ('heritage', 'Heritage')], max_length=20)),
                ('dialect_notes', models.TextField(blank=True, default='')),
                ('consent_app_use', models.BooleanField(default=False)),
                ('consent_language_preservation', models.BooleanField(default=False)),
                ('consent_ml_training', models.BooleanField(default=False)),
                ('consent_attribution', models.CharField(choices=[('name', 'By Name'), ('anonymous', 'Anonymous')], default='anonymous', max_length=20)),
                ('consent_timestamp', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
