# Generated by Django 5.1.15 on 2026-03-22 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recordings', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='speaker',
            name='email',
            field=models.EmailField(blank=True, default='', help_text='Optional. For volunteer re-engagement and contribution notifications.', max_length=254),
        ),
    ]
